site_name: MkDocs Risonia Thema
site_url: https://unverbuggt.rüthlein.de/risonia/
site_author: René Rüthlein

theme:
    name: risonia
    custom_dir: theme_override/
    logo: img/logo.svg
    favicon: img/logo.ico
    extlink: true
    extblank: true
    manifest: manifest.json
    serviceworker: service-worker.js

extra_javascript:
  - 'assets/javascripts/highlight.min.js'
  - 'assets/javascripts/tablesort.js'
  - 'assets/javascripts/tablesort.number.js'

extra_css:
  - 'css/fonts.css'

nav:
    - 'index.md'
    - 'theme.md'
    - 'markdown.md'
    - Farben:
      - 'colors/index.md'
      - 'colors/primary.md'
      - Zweitfarben:
        - 'colors/secondary/index.md'
        - 'colors/secondary/mono.md'
        - 'colors/secondary/analogous.md'
        - 'colors/secondary/analogous2.md'
        - 'colors/secondary/complementary.md'
        - 'colors/secondary/complementary2.md'
        - 'colors/secondary/triadic.md'
        - 'colors/secondary/triadic2.md'
        - 'colors/secondary/compound.md'
        - 'colors/secondary/compound2.md'
    - Erweiterungen:
        - 'extensions/static-i18n.md'
        - 'extensions/encryptcontent.md'
        - 'extensions/webfonts.md'
        - Javascript:
          - 'extensions/hljs.md'
          - 'extensions/tablesort.md'

plugins:
    - mkdocs-simple-hooks:
        hooks:
          on_post_build: "hooks:get_external_assets"

    - search:
        lang: de

    - i18n:
        default_language: de
        default_language_only: false
        docs_structure: suffix
        languages:
          default:
            name: Deutsch
            build: true
          en:
            name: English
            build: true
            site_name: "MkDocs Risonia theme"
        nav_translations:
          en:
            Farben: Colors
            Zweitfarben: Secondary colors
            Erweiterungen: Extensions
            Javascript: Javascript

    - color-theme:
        theme_color: '#ef6110'
        secondary_color: 'complementary'
        extra_css_light: 
          - 'extra_css/stackoverflow-light.min.css'
          - 'extra_css/tablesort-light.css'
        extra_css_dark: 
          - 'extra_css/stackoverflow-dark.min.css'
          - 'extra_css/tablesort-dark.css'

    - w3css-classes: {}

    - encryptcontent:
        title_prefix: ''
        summary: 'Encrypted Test Page.'
        placeholder: '12345'
        decryption_failure_message: 'Wrong password, please enter "12345".'
        encryption_info_message: 'Please enter "12345".'
        input_class: 'w3-input'
        button_class: 'w3-button w3-theme-l1 w3-hover-theme'
        hljs: False
        arithmatex: False
        mermaid2: False
        remember_password: true
        session_storage: true
        encrypted_something:
          myNav: [div, id]
          myToc: [div, id]
          myTocButton: [div, id]
        search_index: 'dynamically' #dynamically
        password_button: True
        password_button_text: 'ENTER'
        selfhost: true
        selfhost_download: false

repo_url: https://github.com/unverbuggt/mkdocs-risonia-theme

markdown_extensions:
    - attr_list