site_name: MkDocs Risonia Thema
site_url: https://unverbuggt.rüthlein.de/risonia/
site_author: René Rüthlein

theme:
    name: risonia
    custom_dir: theme_override/
    logo: img/logo.svg
    favicon: img/logo.ico
    extlink: true
    extblank: true
    manifest: manifest.json
    serviceworker: service-worker.js
    zoom_img: true
    lazy_img: false

extra_javascript:
  - 'assets/javascripts/highlight.min.js'
  - 'assets/javascripts/tablesort.js'
  - 'assets/javascripts/tablesort.number.js'

extra_css:
  - 'css/fonts.css'

nav:
    - 'mkdocs.md'
    - 'index.md'
    - Markdown: 'markdown.md'
    - Farben:
      - 'colors/index.md'
      - 'colors/primary.md'
      - Zweitfarben:
        - 'colors/secondary/index.md'
        - 'colors/secondary/mono.md'
        - 'colors/secondary/analogous.md'
        - 'colors/secondary/analogous2.md'
        - 'colors/secondary/complementary.md'
        - 'colors/secondary/complementary2.md'
        - 'colors/secondary/triadic.md'
        - 'colors/secondary/triadic2.md'
        - 'colors/secondary/compound.md'
        - 'colors/secondary/compound2.md'
    - Erweiterungen:
        - 'extensions/static-i18n.md'
        - 'extensions/encryptcontent.md'
        - 'extensions/webfonts.md'
        - Javascript:
          - 'extensions/hljs.md'
          - 'extensions/tablesort.md'

plugins:
    - exclude:
        glob:
          - '*.tmp'

    - mkdocs-simple-hooks:
        hooks:
          on_post_build: "hooks:get_external_assets"

    - mkdocs-video:
        is_video: True
        video_autoplay: True
        video_loop: True
        css_style:
          width: "50%"

    - search:
        lang: de

    - i18n:
        docs_structure: folder
        fallback_to_default: true
        languages:
          - locale: de
            default: true
            name: Deutsch
            build: true
          - locale: en
            name: English
            build: true
            site_name: "MkDocs Risonia theme"
            nav_translations:
              Erweiterungen: Extensions
              Farben: Colors
              Javascript: Javascript
              Markdown: Markdown
              Zweitfarben: Secondary colors
        reconfigure_material: false
        reconfigure_search: true

    - color-theme:
        theme_color: '#ef6110'
        secondary_color: 'complementary'
        extra_css_light: 
          - 'extra_css/stackoverflow-light.min.css'
          - 'extra_css/tablesort-light.css'
        extra_css_dark: 
          - 'extra_css/stackoverflow-dark.min.css'
          - 'extra_css/tablesort-dark.css'
        additional:
          - theme_color: '#44bb4f'
            secondary_color: 'complementary'

    - w3css-classes: {}

    #- privacy: {}

    - encryptcontent:
        title_prefix: ''
        summary: 'Verschlüsselte Testseite.'
        placeholder: '12345'
        placeholder_user: Benutzer
        password_button_text: 'ENTER'
        decryption_failure_message: 'Falsches Passwort, bitte "12345" eingeben.'
        encryption_info_message: 'Bitte "12345" eingeben.'
        input_class: 'w3-input'
        button_class: 'w3-button w3-theme-l1 w3-hover-theme'
        hljs: False
        arithmatex: False
        mermaid2: False
        remember_password: true
        session_storage: true
        encrypted_something:
          myNav: [div, id]
          myToc: [div, id]
          myTocButton: [div, id]
        search_index: 'dynamically' #dynamically
        password_button: True
        selfhost: true
        selfhost_download: true
        selfhost_dir: 'theme_override'
        reload_scripts:
          - '#theme'
          - '#autostart'
        translations:
          en:
            title_prefix: ''
            summary: 'Encrypted Test Page.'
            placeholder: '12345'
            placeholder_user: User
            password_button_text: 'ENTER'
            decryption_failure_message: 'Wrong password, please enter "12345".'
            encryption_info_message: 'Please enter "12345".'
        password_inventory:
          test: '12345'
          classified: 'password1'
          confidential:
            - 'password2'
            - 'password3'
          secret:
            user4: 'password4'
            user5: 'password5'
        webcrypto: true
        sign_files: 'risonia-theme.json'


repo_url: https://github.com/unverbuggt/mkdocs-risonia-theme

markdown_extensions:
    - attr_list
    - pymdownx.escapeall:
        hardbreak: true