site_name: MkDocs Basic theme
theme:
    name: w3csstheme
    custom_dir: files/
    logo: img/logo.svg

plugins:
    - color-theme:
        theme_color: '#ff0000'

repo_url: https://github.com/unverbuggt/mkdocs-w3css-theme
