site_name: MkDocs Basic theme
site_url: https://epwg.de/test
theme:
    name: w3csstheme
    custom_dir: files/
    logo: img/logo.svg

plugins:
    - color-theme:
        theme_color: 'FF6633'
    - search: {}

repo_url: https://github.com/unverbuggt/mkdocs-w3css-theme
